name: CI Pipeline

# 봇이 작동 조건 설정 (Main 브랜치에 코드가 올라올 때)
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-lint:
  # GitHub 무료 제공 최신 리눅스 사용
    runs-on: ubuntu-latest

    steps:
      - name: 1. Get my codes from GitHub (Checkout)
        uses: actions/checkout@v4

      - name: 2. Node.js env. settings
        uses: actions/setup-node@v4
        with:
            node-version: "22" # latest LTS version
            cache: "npm" # increases pacage install speed

      - name: 3. package install
        run: npm ci

      - name: 4. ESLint code check
        run: npm run lint

      - name: 5. Project build test
        run: npm run build